name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      testSet:
        type: choice
        description: 'Test set'
        required: true
        options:
          - UI
          - API
  
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22.6.0
    - name: Cache node modules and playwright
      uses: pat-s/always-upload-cache@v3.0.1
      id: playwright-cache
      with:
        path: |
          **/node_modules
          ~/.cache/ms-playwright
        key: automation-cache-${{ hashFiles('./package-lock.json') }}  
    - name: Install dependencies
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npm ci
    - name: Install Playwright Browsers
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps

    - name: Running UI tests
      if: ${{ github.event.inputs.testSet!='UI'}}
      run: npx playwright test tests/ui
      #env:
      #  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      #  MAILOSAUR_API_KEY: ${{ secrets.MAILOSAUR_API_KEY }}
    - name: Running API tests
      if: ${{ github.event.inputs.testSet!='API'}}
      run: npx playwright test tests/api
      #env:
      #  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      #  MAILOSAUR_API_KEY: ${{ secrets.MAILOSAUR_API_KEY }}
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 5  
